repos:
-   repo: https://github.com/adamchainz/blacken-docs
    rev: "1.16.0"
    hooks:
    -   id: blacken-docs
        additional_dependencies:
        - black==22.12.0
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    -   id: black
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.0.286
  hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]

- repo: https://github.com/compilerla/conventional-pre-commit
  rev: v2.4.0
  hooks:
    - id: conventional-pre-commit
      stages: [commit-msg]
      args: []
